### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by maticzav** [mgrip/react-cli#3]
Hey 👋,

Thank you for building this fantastic project! I saw you implemented it using `flow` which would be, at least for me, one of the major selling points to switch from `ink`. Do you think you could also add support for typescript?

Let me know if I can help in any way, I would love to rewrite [emma-cli](https://github.com/maticzav/emma-cli) in `react-cli` 🎉

**Comment by mgrip** [comment]
Hi @maticzav, thanks for the interest and opening this issue!

Would you mind clarifying what you mean by supporting typescript? Even though this library is written using flow, its still compiled to native js ([code link](https://github.com/mgrip/react-cli/tree/master/lib)), so I think it should work just fine with any projects using typescript? I haven't actually tried a workflow like that myself so let me know if you're running into any specific issues - definitely want to make sure this library works no matter what platforms people are using!

**Comment by maticzav** [comment]
Definitely, I was thinking more in terms of getting type safety which `flow` features. That's why I was wondering about `TypeScript` support. I have no doubt that `react-cli` would work if I used the compiled code but I can already do that in `ink` and get a dozen premade components on top of it. Did that clarify the idea? 🙂

**Comment by mgrip** [comment]
Ahh yes got it, thanks! 😄 I've never published typescript definitions for a module before but I'm assuming that should definitely be doable. Now that you mention it I believe I need to do some work for flow as well to make sure those types are available when using this with flow-typed projects. I'll leave this issue open for typescript and open a new one for flow. If you have any suggestions or want to help with a PR for either, feel free!

**Comment by mgrip** [comment]
Typescript instructions: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by cspotcode** [comment]
Can flow emit TypeScript declarations?  Or are there tools to auto-convert flow declarations to TypeScript declarations?  If so, you can bundle them in the package published to npm.

**Comment by mgrip** [comment]
Unfortunately I'm not aware of any tools like that @cspotcode. Shouldn't be too difficult to write up a typescript definition file though and include it with this package, just need to get around to it. If you or anyone else wants to take a crack at it feel free to throw up a PR!
